/* Each new term in the fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89,...
By considering the terms in the Fibonacci sequence whose values do not exceed four milion, 
find the sum of the even-valued terms. */
//######################################

#include <stdio.h>

int main(){
    const int MAX_VALUE = 4000000;
    int prev_term = 0,  next_term = 1; //next & previous term
    int new_term = 0;
    int sum = 0; // for sum of the even-value 
    
    while(new_term <= MAX_VALUE){
        //This variable holds a new sentece created from the previous and next ones.
        new_term = prev_term + next_term;
        printf("%d\n", new_term);//print new sequence
        if (new_term % 2 == 0)  //if new_term is even 
            sum += new_term;
        prev_term = next_term;
        next_term = new_term;
    }
    
    printf("sum of even-valued terms: %d\n", sum);

    return 0;
}
